name: Publish Package to testpypi

on:
  workflow_call:
    secrets:
      TEST_PYPI_API_TOKEN:
        required: true

jobs:
  publish:
    name: Publish package
    runs-on: ubuntu-latest
    environment: test_pypi
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: ./dist/
      - uses: pypa/gh-action-pypi-publish@v1.5.2
        with:
          user: __token__
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
